- name: Import Playbook Exemplo
  hosts: all
  tasks:
  - name: Criando arquivo de teste
    ansible.builtin.file:
      path: /tmp/foo.conf
      state: touch

- name: Instalar pacotes a partir do import_tasks
  import_playbook: install-packages.yaml
