- hosts: all
  gather_facts: False
  vars:
    pacotes:
      - git
      - telnet
      - tree

  tasks:
  - name: Instalando Pacotes
    package: 
      name: "{{ item }}"
      state: present
    with_items: "{{ pacotes }}"

